import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from './utils/next_ui_provider';
import Nav from '@components/nav';
import IsVotingTimeProvider from './utils/is_voting_time_provider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='bg-custom_blue'>
    <body>
      <IsVotingTimeProvider currentDate={new Date()}>
          <Providers>
              <Nav />
              <main>
                {children}
              </main>
          </Providers>
      </IsVotingTimeProvider>
    </body>
  </html>
  );
}
